### PR TITLE
- change GQLS fields support closure

### PR DESCRIPTION
**Pull request by kudorori**
Hello.
I have a reference [https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L415](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L415)

Made a partial modification so that it can support the Closure feature.

### CODE REVIEW

**Comment by sarkistlt** [comment]
Hi, thanks for contribution, but you are not returning correct fields object. Can you check this gist with fix. [](https://gist.github.com/sarkistlt/5d41c6a3a6d8a6c23599415faaa853f1) And commit it, then I can merge your pull request. Thanks.

**Comment by kudorori** [comment]
I do not understand what you mean, I am using this, he works for me 🤔🤔

**Comment by kudorori** [comment]
I think I know where the error is, this is a low-level error, please wait for me to fix 😅😅

**Comment by kudorori** [comment]
I added a new parameter ExtendForClosure, which he can use to solve my problem 😅😅 (Type Cycle dependency)

the example
```javascript
createType({
  name: "userType",
  schema: user,
  class: "GraphQLObjectType",
  extendForClosure: () => ({
    getHotel: {
      type: hotelType
    }
  })
})
```

**Comment by sarkistlt** [comment]
[Here the fix](https://gist.github.com/sarkistlt/5d41c6a3a6d8a6c23599415faaa853f1), sorry forgot to attach link in the first comment. Issue is that `GQLS.fields` will fetch `fields` object only when executed, and will get that object from the scope which is not obvious and preferred approach, especially if we have more simple and obvious way how to do that.

**Comment by kudorori** [comment]
please close the a pull request .  😅😅
i have finished a library for me 😊

**Pull request closed without merging**
